### PR TITLE
Use new GTAA SPARQL endpoint

### PR DESCRIPTION
**Pull request by ddeboer**
- added one GTAA dataset for testing
- added query variable as filter

### CODE REVIEW

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+      "@value": "GTAA Persoonsnamen"
+    }
+  ],
+  "creator": [
+    {
+      "@id": "https://www.beeldengeluid.nl/"
+    }
+  ],
+  "url": [
+    "http://data.beeldengeluid.nl/gtaa/Persoonsnamen"
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld:17]: Is this indeed correct, that is do all Persoonsnamen concepts begin with this URL prefix? If so, this will solve #492.

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld [hunk 2]
```diff
@@ -0,0 +1,37 @@
+{
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld:1]: Please use dashes `-` the filenames, as we already had for the old version of the GTAA endpoint: `genre-filmmuseum.jsonld`.

**Review by ddeboer — COMMENTED** [review]
Please make sure the filenames of the `.rq` files match those in the `jsonld` data. Use dashes `-` (not underscore `_`) everywhere for consistency.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld [hunk 3]
```diff
@@ -0,0 +1,37 @@
+{
+  "@context": "https://schema.org/docs/jsonldcontext.jsonld",
+  "@id": "http://data.beeldengeluid.nl/gtaa/OnderwerpenBenG",
+  "@type": "Dataset",
+  "name": [
+    {
+      "@language": "nl",
+      "@value": "GTAA Onderwerpen beeld-geluid"
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld:8]: This is a slightly weird name.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_namen.jsonld [hunk 4]
```diff
@@ -0,0 +1,37 @@
+{
+  "@context": "https://schema.org/docs/jsonldcontext.jsonld",
+  "@id": "http://data.beeldengeluid.nl/gtaa/Namen",
+  "@type": "Dataset",
+  "name": [
+    {
+      "@language": "nl",
+      "@value": "GTAA Namen"
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/gtaa_namen.jsonld:8]: We tend to use colon `:` to indicate subsets, so we had `GTAA: geografische namen` for example. Does that make sense or is the official name really `GTAA Namen`?

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld [hunk 5]
```diff
@@ -0,0 +1,37 @@
+{
+  "@context": "https://schema.org/docs/jsonldcontext.jsonld",
+  "@id": "http://data.beeldengeluid.nl/gtaa/Genre_Filmmuseum",
+  "@type": "Dataset",
+  "name": [
+    {
+      "@language": "nl",
+      "@value": "Genre Filmmuseum"
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld:8]: Should `GTAA` be part of this name? `Genre Filmmuseum` looks really weird. Did you mean: `Genres Filmmuseum`?

**Comment by ddeboer** [comment]
I cannot test these queries locally (because I have no access to the SPARQL endpoint), so I’m assuming they are correct.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld (hunk 1 above)
Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld:17]: This does not seem to be the case, e.g. https://data.beeldengeluid.nl/gtaa/30369 of Genre Filmmuseum does not start with `http://data.beeldengeluid.nl/gtaa/Genre_Filmmuseum` (the URL that is defined below for this dataset).

Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld:17]: Concept URI's all start with the same prefix: http://data.beeldengeluid.nl/gtaa/{some_id}
So, Person names don't have a different prefix that geographical names, for example.

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld (hunk 2 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld:1]: Is it ok that I remove the older GTAA files and replace them with the newer ones, including dashes?

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld (hunk 3 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld:8]: That is what it is referred to. And indeed confusing. It has nothing to do with the Instituut voor Beeld en Geluid, but its just that terms from these lists are more focussing on things that can be seen (beeld) or can be heard (sound). The ohter Onderwerpen axis is abstracting away from physical and concrete stuff. E.g. When you see a 'Suzuki' the more general subject will be 'Cars'. The beeld-geluid axis would sooner accept more specific instances of concepts. I hope this example helps.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_namen.jsonld (hunk 4 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_namen.jsonld:8]: I will update conform your suggested format.

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld (hunk 2 above)
Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld:1]: Yes!

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld (hunk 1 above)
Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld:17]: The dataset’s `schema:url` must be its URL prefix, so that would be `http://data.beeldengeluid.nl/gtaa/` for all datasets, if I understand you correctly. This prefix is used for looking up terms by their URI. Unfortunately, if all datasets share the same prefix, #492 will not be solved. Is there perhaps a generic SPARQL endpoint for lookups in all datasets, or do lookups need to go to the individual endpoints?

(Our property name `schema:url` is slightly unclear, but we decided to stick with pure Schema.org for now, even if it’s less expressive. See also #491.)

File: packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+  "distribution": [
+    {
+      "@id": "https://data.beeldengeluid.nl/id/datadownload/0033",
+      "@type": "DataDownload",
+      "contentUrl": "https://gtaa.apis.beeldengeluid.nl/sparql",
+      "encodingFormat": "application/sparql-query",
+      "potentialAction": [
+        {
+          "@type": "SearchAction",
+          "query": "file://catalog/queries/search/genre-filmmuseum.rq"
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq:28]: The actual file names still have underscores, causing the automated tests to fail on GH Actions.

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld (hunk 5 above)
Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld:8]: It’s okay to add non-GTAA datasets, of course. I’m just wondering if this dataset is _only_ being used by Filmmuseum or are other institution also using it or going to use it?

File: packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+    {
+      "@id": "https://www.beeldengeluid.nl/"
+    }
+  ],
+  "url": [
+    "http://data.beeldengeluid.nl/gtaa/Genre_Filmmuseum"
+  ],
+  "distribution": [
+    {
+      "@id": "https://data.beeldengeluid.nl/id/datadownload/0033",
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq:21]: Should these IRIs be resolvable? Currently they are not.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld (hunk 3 above)
Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld:8]: It does. The name still needs the colon `:` for consistency.

File: packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq (hunk 7 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq:21]: yes, now they are. the data catalog needed to be updated.

File: packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq (hunk 6 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq:28]: they are not in the local branch. I just removed the dataset files that had underscores and pushed. query files with underscores I don't see.

File: packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld (hunk 5 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/genre_filmmuseum.jsonld]: I only know of EYE as a user of Genres Filmmuseum.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld (hunk 3 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_onderwerpen_beng.jsonld]: It has a colon locally. Can you check again? Maybe it was fixed in the latest push. We should be in sync.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld (hunk 1 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: It doesn't seem right to use the schema:url property for the prefix. The schema:url is the address for the resource. Because the GTAA parts are organised around ConceptSchemes, In our case the ConceptScheme address is the resource. 

But, one could also argue that the Dataset is the resource, and therefore the schema:url should be
``  "url": [
    "https://data.beeldengeluid.nl/id/dataset/0010"
  ],
`` and maybe the ID should also be:
``
  "@id": "https://data.beeldengeluid.nl/id/dataset/0010",
  "@type": "Dataset",
``

I would prefer to use the dataset ID as the schema:``@id``, and the ConceptScheme URI as schema:url

``
  "@id": "https://data.beeldengeluid.nl/id/dataset/0010",
  "@type": "Dataset",
``
``  "url": [
    "http://data.beeldengeluid.nl/gtaa/OnderwerpenBenG"
  ],
`` 

But, then there is no prefix for lookup. Why is that necessary anyway? The Concepts all have a proper URI, so why would you need a prefix? For your information: the GTAA Concepts are all dereferanceable using the URI. Isn't that enough for lookup? Also, no basic auth is required for that.

File: packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq [hunk 8]
```diff
@@ -0,0 +1,37 @@
+{
```
Comment (ddeboer) [inline packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq:1]: This file should have extension jsonld, not rq.

Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/filmmuseum-genres.rq]: sorry. that was a bit sloppy of me. should be fixed.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld (hunk 1 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: Sorry, my response might have unintentionally sounded a bit agitated at the end. I just wondered why you need the prefix.

Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: I’ve just [added some documentation](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-catalog#data-model) to explain the need for the prefix. The Network of Terms has its own lookup functionality to present the same SKOS representation to clients as when they search for terms. Lookup is needed because:

- some sources dereference URIs correctly but return it in their own vocabulary, such as Schema.org, rather than SKOS, which clients expect from the Network of Terms
- other sources use SKOS internally but fail to dereference URIs, including GTAA (as of now):

      $ curl -v -H Accept:application/ld+json https://data.beeldengeluid.nl/gtaa/30369
      < HTTP/1.1 500 Internal Server Error
      
      Could not find acceptable representation

- even if sources dereference correctly and use SKOS, they may return values different from those returned by the Network of Terms search, which can be confusing for clients.

To know which term to source for a certain URI, the Network of Terms needs to know those prefixes.

Does that clear things up?

**Comment by wmelder** [comment]
The GTAA URIs have HTTP as protocol, not https. They can be dereferenced without any authentication.



Verstuurd vanaf mijn iPhone

**Comment by wmelder** [comment]
The Genre_Filmmuseum dataset can be left out of the network of terms for now. I will prepare a commit for that.

File: packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld (hunk 1 above)
Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: Please note that the GTAA URI's all have the HTTP protocol. We should provide a better return code when using HTTPS for dereferencing.

``To know which term to source for a certain URI, the Network of Terms needs to know those prefixes.``
I still don't get it. Why do you need the prefix? For all sources it is different what the path after that prefix is. In our case the skos:notation value is always corresponding to it: ``/gtaa/{skos:notation}``. But that is not what is needed to dereference the concept. You can use the whole Concept URI (always HTTP) to get the data. Also, there is an API that can be used to get the concept data, but that is not involved at all in the network of terms. Given the queries in ``catalog/queries/lookup/`` and the documentation that you added: ``lookup queries retrieve a single term based on its URI.`` I would deduct that the SPARQL endpoint is used to get the Concept data. Why define a prefix then? It is just our GTAA namespace, not an API function.

Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: > Please note that the GTAA URI's all have the HTTP protocol.

Ah, good to know! However, `curl -v -L -H Accept:application/ld+json http://data.beeldengeluid.nl/gtaa/30369` still returns a 500 error.

Anyway, the lookup feature works like this. On https://termennetwerk.netwerkdigitaalerfgoed.nl/lookup, a user enters any term’s URI, for example `http://vocab.getty.edu/aat/300046300` or `http://data.beeldengeluid.nl/gtaa/30369`. 

The question is: how does the Network of Terms know _which SPARQL endpoint to consult_ for each URI? This is what we need the URI prefix for:

- `http://vocab.getty.edu/aat/...` goes to the AAT endpoint;
- `http://data.beeldengeluid.nl/gtaa/...` to the GTAA one.

Does that make sense?

Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: >Ah, good to know! However, curl -v -L -H Accept:application/ld+json http://data.beeldengeluid.nl/gtaa/30369 still returns a 500 error.

Sorry to hear that. Now that you bring it up, I realize that I brought up that issue some time ago. It is acknowledged as a bug that it doesn't provide JSON-LD. It will give you the XML representation: ``curl  -L -H Accept:application/rdf+xml http://data.beeldengeluid.nl/gtaa/30369

Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: >if the URI begins with http://data.beeldengeluid.nl/gtaa/..., retrieve it from the GTAA endpoint (and so on).
Does that make sense?

I was under the impression that the lookup function was a type of query 'per source'. Now I understand that you do some delegation of the concept URI dereferencing 'by using the schema prefix'. In that case, for any of the GTAA sources it holds that any GTAA URI can be resolved and then ``http://data.beeldengeluid.nl/gtaa`` is the prefix for ALL GTAA sources. And they all use the same SPARQL endpoint, so all concepts are in all endpoints. 
The difficulty for the network of terms is that if many sources share the same prefix, which one does it need to choose?
Luckily, the solution is easy: If we make sure all GTAA lookup queries are not filtering on ConceptScheme it doesn't matter what source you choose: any GTAA source is good.
So, if you agree that this is the solution for the network of terms, than I will make the changes and commit. This means I remove all the triples like this: ``    ?uri skos:inScheme <http://data.beeldengeluid.nl/gtaa/GeografischeNamen> . ``

Comment (ddeboer) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: Please go ahead! You can then also reduce the lookup queries to a single one, and use that from all datasets. (I’ve already done this for the search queries.)

Comment (wmelder) [reply packages/network-of-terms-catalog/catalog/datasets/gtaa_persoonsnamen.jsonld]: All GTAA lookup queries share the same file now.

**Comment by wmelder** [comment]
After merging master into branch these errors arise when running `npm dev`:
>10:55:51 AM - File change detected. Starting incremental compilation...
../network-of-terms-catalog/src/catalog.ts(11,9): error TS2595: 'globby' can only be imported by using a default import.
../network-of-terms-catalog/src/catalog.ts(104,15): error TS7006: Parameter 'file' implicitly has an 'any' type.
10:55:52 AM - Found 2 errors. Watching for file changes.

**Comment by ddeboer** [comment]
And… merged. Thanks a lot for your contribution and patience @wmelder!
